name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile --check-files --network-timeout 600000

      - name: Run lint
        run: yarn lint

      - name: Lint YAML files
        run: yarn lint:yaml

      - name: Type check
        run: yarn type-check

      - name: Run tests
        run: yarn test --watchAll=false

      - name: Build Next.js app
        run: yarn build
